### ISSUE TITLE
undefined method `tree' for #<Mail::Address:44286800 Address: |lisinge@gmail.com| >

### ISSUE THREAD

**Issue by hugodias** [lisinge/valid_email2#12]
I'm getting this error when i try to validate an record without ActiveRecord:

```
NoMethodError: undefined method `tree' for #<Mail::Address:44286800 Address: |lisinge@gmail.com| >
```
This error rises when i try to use `.valid?`

```
address = ValidEmail2::Address.new("lisinge@gmail.com")
address.valid?
NoMethodError: undefined method `tree' for #<Mail::Address:44286800 Address: |lisinge@gmail.com| >
	from /home/vagrant/.rvm/gems/ruby-2.1.2/gems/valid_email2-1.0.0/lib/valid_email2/address.rb:24:in `valid?'
	from /home/vagrant/.rvm/gems/ruby-2.1.2/gems/valid_email2-1.0.0/lib/valid_email2/address.rb:38:in `valid_mx?'
	from (irb):8
```

rails (4.1.6)
mail (2.6.1)
ruby 2.1.2

**Comment by dimitko** [comment]
FYI, my solution from above came back to bite me after a few other gems wanted a more contemporary version of the `mail` gem, so I ended up using the `email_validator` gem eventually.

**Comment by lisinge** [comment]
Alright, i just pushed version 1.1.5 to rubygems which works with version 2.6 of the mail gem so this shouldn't be a problem anymore :)

email_validator is nice but it's lacking mx validation and the blacklist functionality
